import { auth } from "@clerk/nextjs/server";
import { UserRole } from "@prisma/client";

import "./admin.css";

import { Sidebar } from "./_components/sidebar";
import { Container } from "./_components/container";
import { getSelf } from "@/lib/current-user";
// import { ModalProvider } from "./_components/providers/modal-provider";

// const AdminLayout = async ({ children }: { children: React.ReactNode }) => {
//   const user = await getSelf();

//   if (!user) {
//     return auth().redirectToSignIn({
//       returnBackUrl: "http://localhost:3000/admin",
//     });
//   }

//   if (user.role === UserRole.USER) {
//     return auth().redirectToSignIn({
//       returnBackUrl: "http://localhost:3000/admin",
//     });
//   }

//   return (
//     <div className="relative h-full overflow-hidden bg-background">
//       <Sidebar />
//       <Container>{children}</Container>
//       <ModalProvider />
//     </div>
//   );
// };

// export default AdminLayout;

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
// import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ToastProvider } from "@/components/providers/toast-provider";
import { QueryProvider } from "./_components/providers/query-provider";
import { ModalProvider } from "./_components/providers/modal-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getSelf();

  if (!user) {
    return auth().redirectToSignIn({
      returnBackUrl: "http://localhost:3000/admin",
    });
  }

  if (user.role === UserRole.USER) {
    return auth().redirectToSignIn({
      returnBackUrl: "http://localhost:3000/admin",
    });
  }

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            disableTransitionOnChange
          >
            <ToastProvider />
            <QueryProvider>
              <div className="relative h-full overflow-hidden bg-background">
                <Sidebar />
                <Container>{children}</Container>
                <ModalProvider />
              </div>
            </QueryProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
