import { Mulish } from "next/font/google";

import "./home.css";

import { Navbar } from "@/components/navbar/navbar";
import { cn } from "@/lib/utils";
import Footer from "./_components/footer";

const mulish = Mulish({ subsets: ["latin"] });

// const HomeLayout = async ({ children }: { children: React.ReactNode }) => {
//   return (
//     <div className={cn(`h-full`, mulish.className)}>
//       <Navbar />
//       <main className="pt-20">{children}</main>
//       <Footer />
//     </div>
//   );
// };

// export default HomeLayout;

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
// import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ToastProvider } from "@/components/providers/toast-provider";
import { QueryProvider } from "../(admin)/_components/providers/query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            disableTransitionOnChange
          >
            <ToastProvider />
            <QueryProvider>
              <div className={cn(`h-full`, mulish.className)}>
                <Navbar />
                <main className="pt-20">{children}</main>
                <Footer />
              </div>
            </QueryProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
